=============================================================================
STUDENT 1 — AUDIO ANALYST (BUILT FROM SCRATCH)
Multimodal Crime / Incident Report Analyzer
AI for Engineers — Group Assignment
=============================================================================
DATASET: 911 Recordings — The First 6 Seconds (Kaggle)
HOW TO USE:
1. Go to kaggle.com → search "911 Recordings The First 6 Seconds"
2. Click the dataset → Add to notebook via "+ Add Input"
3. Upload THIS notebook to Kaggle
4. Make sure Internet is ON in Session options
5. Run All cells

STRUCTURE (following assignment tip):
PART 1 → Transcription using Whisper (speech to text)
PART 2 → Keyword extraction + sentiment + urgency ON TOP of transcripts
=============================================================================

### Install All Dependencies

In [11]:
!pip install openai-whisper spacy transformers torch pandas -q
!python -m spacy download en_core_web_sm -q
print("✔ All dependencies installed")

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 803.2/803.2 kB 21.7 MB/s eta 0:00:0000:01
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 188.3/188.3 MB 9.2 MB/s eta 0:00:00:00:0100:01
  Building wheel for openai-whisper (pyproject.toml) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 71.5 MB/s eta 0:00:0000:0100:01
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.
✔ All dependencies installed

### Imports

In [12]:
import os
import glob
import warnings
import pandas as pd
import whisper
import spacy
import torch
from transformers import pipeline

warnings.filterwarnings("ignore")
print("✔ Imports done")

# =============================================================================
#  PART 1 — TRANSCRIPTION (Whisper Speech-to-Text)
#  Following assignment tip: "Run transcription first"
# =============================================================================

✔ Imports done

### Scan Audio Files

In [13]:
print("=" * 55)
print("  PART 1 — TRANSCRIPTION")
print("=" * 55)

# Find all audio files in the Kaggle dataset input folder
all_files   = glob.glob("/kaggle/input/**/*", recursive=True)
audio_files = sorted([f for f in all_files if f.endswith(".wav") or f.endswith(".mp3")])
csv_files   = sorted([f for f in all_files if f.endswith(".csv")])

print(f"  Audio files found : {len(audio_files)}")
print(f"  CSV files found   : {len(csv_files)}")

# Show sample
if audio_files:
    print("\n  Sample audio files:")
    for f in audio_files[:5]:
        print(f"    🎙 {os.path.basename(f)}")
else:
    print("\n  ⚠ No audio files found!")
    print("  Add the dataset via '+ Add Input' on the right panel")

=======================================================
  PART 1 — TRANSCRIPTION
=======================================================
  Audio files found : 707
  CSV files found   : 1

  Sample audio files:
    🎙 call_100_0.wav
    🎙 call_101_0.wav
    🎙 call_102_0.wav
    🎙 call_103_0.wav
    🎙 call_104_0.wav

### Load Whisper & Transcribe All Audio

In [14]:
# Whisper is the recommended tool from the assignment
print("\nLoading Whisper speech-to-text model...")
print("(Downloads ~150MB on first run — takes 1-2 minutes)")
whisper_model = whisper.load_model("base")
print("✔ Whisper model loaded\n")

# Transcribe every audio file
raw_transcripts = []

if not audio_files:
    print("⚠ No audio files — using demo transcripts for demonstration")
    raw_transcripts = [
        {"Call_ID": "C001", "Full_Text": "There is a fire people are trapped on second floor of the building on Downtown Avenue please send help immediately"},
        {"Call_ID": "C002", "Full_Text": "There has been a car accident on Main Street near Oak intersection two vehicles involved someone is injured"},
        {"Call_ID": "C003", "Full_Text": "I want to report a robbery at the convenience store on Fifth Avenue the suspect just left with cash"},
        {"Call_ID": "C004", "Full_Text": "Someone has collapsed in River Park near the fountain they are unconscious please send an ambulance"},
        {"Call_ID": "C005", "Full_Text": "There is a large crowd disturbance outside City Hall people are shouting and blocking traffic"},
    ]
else:
    print(f"Transcribing {len(audio_files)} audio files using Whisper...\n")
    for i, audio_path in enumerate(audio_files):
        call_id = f"C{i+1:03d}"
        try:
            print(f"  [{i+1}/{len(audio_files)}] Transcribing {call_id}...")
            result = whisper_model.transcribe(audio_path)
            text   = result["text"].strip()
            raw_transcripts.append({"Call_ID": call_id, "Full_Text": text})
            print(f"  ✔ {call_id}: {text[:70]}...")
        except Exception as e:
            print(f"  ❌ {call_id} failed: {e}")
            raw_transcripts.append({"Call_ID": call_id, "Full_Text": ""})

        if (i + 1) % 10 == 0:
            print(f"\n  ── {i+1}/{len(audio_files)} files transcribed ──\n")

Loading Whisper speech-to-text model...
(Downloads ~150MB on first run — takes 1-2 minutes)

100%|████████████████████████████████████████| 139M/139M [00:00<00:00, 301MiB/s]

✔ Whisper model loaded

Transcribing 707 audio files using Whisper...

  [1/707] Transcribing C001...
  ✔ C001: One just...
  [2/707] Transcribing C002...
  ✔ C002: This is the Blocopia Bank in 1302 with the Transnational Speedway call...
  [3/707] Transcribing C003...
  ✔ C003: Yeah? Yeah. Yeah. Yeah. Yeah. Yeah....
  [4/707] Transcribing C004...
  ✔ C004: Yes, we're at the Nelson building and there's some men here with the b...
  [5/707] Transcribing C005...
  ✔ C005: Listen, we're playing really bad at this. Okay, so get on our track, m...
  [6/707] Transcribing C006...
  ✔ C006: 我是 我是 我是 我是 Dr. Dr. Dr. Your Dr. Dr. Dr. Dr. Dr. Dr Dr. Dr. Dr. Dr. Dr...
  [7/707] Transcribing C007...
  ✔ C007: I'm locking in the field and I'm looking for a champ. You're walking i...
  [8/707] Transcribing C008...
  ✔ C008: On vient se faire voir verser à mes magies. drink...
  [9/707] Transcribing C009...
  ✔ C009: Emersing you've got it, I would always be shut down here um... out fro...
  [10/707] Transcribing C010...
  ✔ C010: Okay, it's out of the bizzani, we'll grab any photos. Okay....

  ── 10/707 files transcribed ──

  [11/707] Transcribing C011...
  ✔ C011: Yes, that's two sub-pro here that's the 8 on the ground. Okay, he did ...
  [12/707] Transcribing C012...
  ✔ C012: I mean, I'll wait behind the... ...and the fighters won't turn off....
  [13/707] Transcribing C013...
  ✔ C013: I'm here at the police station. I'm going to hold. Okay....
  [14/707] Transcribing C014...
  ✔ C014: Yes, ma'am, I need to go out and leave quickly. Down the church. Chang...
  [15/707] Transcribing C015...
  ✔ C015: Ma'am, my cat is a person. I had to go find it....
  [16/707] Transcribing C016...
  ✔ C016: Hello? Hello? Hello? Hello? Oh, that one was......
  [17/707] Transcribing C017...
  ✔ C017: laptops out and can...
  [18/707] Transcribing C018...
  ✔ C018: I need somebody escorted out of my store right away. He's causing prob...
  [19/707] Transcribing C019...
  ✔ C019: Hello! Hello! Hello 911!...
  [20/707] Transcribing C020...
  ✔ C020: I got three people, the second people, thank you. They're taking kids?...

  ── 20/707 files transcribed ──

  [21/707] Transcribing C021...
  ✔ C021: Hey, um, they just woke into my house. They had guns. They told us to ...
  [22/707] Transcribing C022...
  ✔ C022: Um, I took some pills and um, the pills were really good mad, and um.....
  [23/707] Transcribing C023...
  ✔ C023: Alright, well, the thing is, I was just flying with my buddy. You were...
  [24/707] Transcribing C024...
  ✔ C024: If somebody stays with Diane, I'm home alone and he's not here. My dau...
  [25/707] Transcribing C025...
  ✔ C025: I don't have an emergency tube for this stuff, it just left my house j...
  [26/707] Transcribing C026...
  ✔ C026: My house is on fire. I don't know how to sleep in and I'll go to someo...
  [27/707] Transcribing C027...
  ✔ C027: Hi, my name is Maria. I'm calling because my teacher, Mr. Haines,...
  [28/707] Transcribing C028...
  ✔ C028: Yes, I have a gun and I don't it's from LA car loaded and something ju...
  [29/707] Transcribing C029...
  ✔ C029: I have a friend who's been drinking, I've been trying to help him sinc...
  [30/707] Transcribing C030...
  ✔ C030: I'm a police at where the heck am I? 291 water counts, three to immedi...

  ── 30/707 files transcribed ──

  [31/707] Transcribing C031...
  ✔ C031: I'm not sure my friend is called and basically told me she was going t...
  [32/707] Transcribing C032...
  ✔ C032: with the address, 750 south to 50 west....
  [33/707] Transcribing C033...
  ✔ C033: emergency. Fire. Cutting wood. So, what's the location?...
  [34/707] Transcribing C034...
  ✔ C034: It's not my, I mean, I haven't made it, I haven't possible, I haven't ...
  [35/707] Transcribing C035...
  ✔ C035: Back up slowly ai Broken mountains Man...
  [36/707] Transcribing C036...
  ✔ C036: Yeah man, I'm a bit late today and we're in the road. We're going to s...
  [37/707] Transcribing C037...
  ✔ C037: I'm trying to come into 29 and I'm trying to come back to the closest ...
  [38/707] Transcribing C038...
  ✔ C038: Now, I won't let you know that I'm sleepy. But I heard my doorbell rin...
  [39/707] Transcribing C039...
  ✔ C039: Please come down here. What's your, what? I don't know that address. Y...
  [40/707] Transcribing C040...
  ✔ C040: What was your weekend of a playboy end down a month in park? A plane g...

  ── 40/707 files transcribed ──

  [41/707] Transcribing C041...
  ✔ C041: Oh, somebody is coming. Somebody help. What's going on?...
  [42/707] Transcribing C042...
  ✔ C042: Somebody was trying to rob us. She got tight right now. We're holding ...
  [43/707] Transcribing C043...
  ✔ C043: Hello? Hello, I'm floating down the river in my car. Okay, what river ...
  [44/707] Transcribing C044...
  ✔ C044: Yes, I need an ambulance on hard stones. Okay, we're in the airport....
  [45/707] Transcribing C045...
  ✔ C045: with that little boy missing. Have you had any reports on one? No, I'm...
  [46/707] Transcribing C046...
  ✔ C046: We need police. Let's find a bike by 5.23. Let's find on them, man....
  [47/707] Transcribing C047...
  ✔ C047: man please help me I'm a county road 900 to 600 will build the TV towe...
  [48/707] Transcribing C048...
  ✔ C048: I'm working to please my, I'm with you right here at America. I don't ...
  [49/707] Transcribing C049...
  ✔ C049: I'm not a prospect but I need to have somebody go to my brother's hous...
  [50/707] Transcribing C050...
  ✔ C050: one one. Hey, my friend is having a feature. Where are you at?...

  ── 50/707 files transcribed ──

  [51/707] Transcribing C051...
  ✔ C051: Hello? Yes. We've just been robbed. Where? 220,000....
  [52/707] Transcribing C052...
  ✔ C052: High Springs Community School, I called 911 a few minutes ago. We have...
  [53/707] Transcribing C053...
  ✔ C053: Yeah, I need an ambulance to 12 mark in South Reno. Okay, let's go on....
  [54/707] Transcribing C054...
  ✔ C054: And we made a key application, so the whole thing is language-adresse ...
  [55/707] Transcribing C055...
  ✔ C055: 4980. I'm talking to my daughter right now. 4980. I'm talking to my da...
  [56/707] Transcribing C056...
  ✔ C056: It's been a demolishing of a house and there is a woman inside and we ...
  [57/707] Transcribing C057...
  ✔ C057: to help you. Hi, this is Latisha from store Big Five on Green Valley. ...
  [58/707] Transcribing C058...
  ✔ C058: Yes, ma'am, my neighbor just ran over so someone tried to kill her in ...
  [59/707] Transcribing C059...
  ✔ C059: My idea is, since the way you are emotionally abusive me,...
  [60/707] Transcribing C060...
  ✔ C060: Yeah, I've got kind of like a knife. My father don't leave a little bi...

  ── 60/707 files transcribed ──

  [61/707] Transcribing C061...
  ✔ C061: My husband is up in the attic and he's not responding....
  [62/707] Transcribing C062...
  ✔ C062: I need to report a murder. Okay, where is that? 157 red-...
  [63/707] Transcribing C063...
  ✔ C063: Yeah, it's very much right there in the back. I just think I just foun...
  [64/707] Transcribing C064...
  ✔ C064: I'm Joan Pearson and I just killed two people....
  [65/707] Transcribing C065...
  ✔ C065: Hey, I told you some rally. We've got a medical aburge that 4500...
  [66/707] Transcribing C066...
  ✔ C066: I just got back from work. From Target. I'm at 330....
  [67/707] Transcribing C067...
  ✔ C067: Yes, we need an ambulance. We're at Westport Shopping Center right out...
  [68/707] Transcribing C068...
  ✔ C068: No, no, no! No, no! No, no!...
  [69/707] Transcribing C069...
  ✔ C069: Yes, excuse me, so some helicopter is came down. The helicopter came d...
  [70/707] Transcribing C070...
  ✔ C070: Yes, helicopter just crashed. A helicopter just crashed? Yes, sir. I t...

  ── 70/707 files transcribed ──

  [71/707] Transcribing C071...
  ✔ C071: Good enough, Avenue. Someone is running around the neighborhood shooti...
  [72/707] Transcribing C072...
  ✔ C072: Hey, who's it? Sheriff's office can I help you? Yeah, who's this, Gend...
  [73/707] Transcribing C073...
  ✔ C073: of your emergency. A month has spoken to my house and my time is takin...
  [74/707] Transcribing C074...
  ✔ C074: Do I need any of them to please after or won't? Okay, you need a polic...
  [75/707] Transcribing C075...
  ✔ C075: Oh my God, I'm on third Avenue to wherever I'll track somebody just tr...
  [76/707] Transcribing C076...
  ✔ C076: I hopped, there's a sitting on arm, yeah, like we're sitting. Sitting ...
  [77/707] Transcribing C077...
  ✔ C077: No, not based on how this emergency to am......
  [78/707] Transcribing C078...
  ✔ C078: I have just smothered my way....
  [79/707] Transcribing C079...
  ✔ C079: We're on the boat right now. My friend says, got it by the shark. We h...
  [80/707] Transcribing C080...
  ✔ C080: Yes, I got I just shot someone in my business on that 59 31...

  ── 80/707 files transcribed ──

  [81/707] Transcribing C081...
  ✔ C081: We got some shootings over here in Silbeach. Okay, where? The salon in...
  [82/707] Transcribing C082...
  ✔ C082: I just killed someone, a hundred, about 40....
  [83/707] Transcribing C083...
  ✔ C083: Okay, yes, Emily, Katie, and the traffic search. She's in the city of ...
  [84/707] Transcribing C084...
  ✔ C084: I got a report of shooting. Okay, where? Lehigh Hansen for Minette....
  [85/707] Transcribing C085...
  ✔ C085: We need the police here. Okay, what's the address of the emergency? Th...
  [86/707] Transcribing C086...
  ✔ C086: Okay, we've got a fire down here at the Route 7 right here at Abington...
  [87/707] Transcribing C087...
  ✔ C087: I want to tell you what's happening first. I just killed my wife. Ther...
  [88/707] Transcribing C088...
  ✔ C088: What do we say? What happened? I'm sorry, I'm sorry. I'm sorry....
  [89/707] Transcribing C089...
  ✔ C089: We have been shot at a house in South Mim2. We have three children and...
  [90/707] Transcribing C090...
  ✔ C090: Yes, I am. I am in this country. I am in this country....

  ── 90/707 files transcribed ──

  [91/707] Transcribing C091...
  ✔ C091: I'm behind the Noseville for Vata, license plate, CEG 8148, and we've ...
  [92/707] Transcribing C092...
  ✔ C092: 4202 Mallor circle. Two men have just crossed my fence to try....
  [93/707] Transcribing C093...
  ✔ C093: What city are you in?...
  [94/707] Transcribing C094...
  ✔ C094: I am going eastbound on I-10 between LA-30 and LA-44....
  [95/707] Transcribing C095...
  ✔ C095: Yes, we need officer right now. There's a man shooting at the lady. We...
  [96/707] Transcribing C096...
  ✔ C096: Yes, ma'am. This is a shoulder. Yes, ma'am....
  [97/707] Transcribing C097...
  ✔ C097: your meditation. I am a little boy having a new name. Let me get a gun...
  [98/707] Transcribing C098...
  ✔ C098: Okay, I call before and I already pay in back. All right, so aren't we...
  [99/707] Transcribing C099...
  ✔ C099: Yeah, I'm putting myself in for my husband, the number....
  [100/707] Transcribing C100...
  ✔ C100: I'm someone's breaking into my house. Wish I'd grab. Sophie, six, seve...

  ── 100/707 files transcribed ──

  [101/707] Transcribing C101...
  ✔ C101: I know. I'm sorry, Gordon. I know when she shot me with... I can go....
  [102/707] Transcribing C102...
  ✔ C102: Yes, sir. I've got this middle school. We have a student with a dunkin...
  [103/707] Transcribing C103...
  ✔ C103: I'm not sure if I'm going to get by train. Why was you hit by a train?...
  [104/707] Transcribing C104...
  ✔ C104: an ambulance to the south side Walmart immediately. What's going on? I...
  [105/707] Transcribing C105...
  ✔ C105: them at Sinocht, and we'll hand them it forward when they see our...
  [106/707] Transcribing C106...
  ✔ C106: I'm hoping. I'll leave in the lab, I think someone is trying to come i...
  [107/707] Transcribing C107...
  ✔ C107: I need a nice grey billed place, I don't care who's 15612....
  [108/707] Transcribing C108...
  ✔ C108: I don't know but you have 4,000...
  [109/707] Transcribing C109...
  ✔ C109: We have a I think we have a dead person in here. Okay. I don't know wh...
  [110/707] Transcribing C110...
  ✔ C110: I'm almost in Wonder Rock, the US bank, and I just need to be sure to ...

  ── 110/707 files transcribed ──

  [111/707] Transcribing C111...
  ✔ C111: What are you? The emergency hotline. Who are you?...
  [112/707] Transcribing C112...
  ✔ C112: It's a business. I believe it's been robbed. What's the name of the bu...
  [113/707] Transcribing C113...
  ✔ C113: and what is your emergency? Hi, my name is Mickey. I'm the manager at ...
  [114/707] Transcribing C114...
  ✔ C114: I think we're on 75. I 75? Yes. Okay....
  [115/707] Transcribing C115...
  ✔ C115: Something is going on. Do you know the south number?...
  [116/707] Transcribing C116...
  ✔ C116: I keep blow-drow. We have blitz. Okay, I'm sorry you have blitz....
  [117/707] Transcribing C117...
  ✔ C117: Are you out of the house yet? No. Or I get out of the house. We can't....
  [118/707] Transcribing C118...
  ✔ C118: emergency. My focus is on that please come. We're going to say the add...
  [119/707] Transcribing C119...
  ✔ C119: Oh, darling, he's ill. Who is this? I told my father right to help....
  [120/707] Transcribing C120...
  ✔ C120: Everyone, im a witches and skip living in the gooood people just don't...

  ── 120/707 files transcribed ──

  [121/707] Transcribing C121...
  ✔ C121: Um, we have somebody. Sorry....
  [122/707] Transcribing C122...
  ✔ C122: I think somebody is breaking in the house. We just came from school an...
  [123/707] Transcribing C123...
  ✔ C123: Um, I always offers, kind of, my mom's on a floor....
  [124/707] Transcribing C124...
  ✔ C124: emergency. I just shot my wife. Can you tell me the address that you'r...
  [125/707] Transcribing C125...
  ✔ C125: I think we need a place at the Walmart Super Center in Miss Kogi. That...
  [126/707] Transcribing C126...
  ✔ C126: Yeah, I need the Polo here. 963, he's 363. There's somebody in the hou...
  [127/707] Transcribing C127...
  ✔ C127: corner of 119 and counting road 1 we just saw plane go down to the...
  [128/707] Transcribing C128...
  ✔ C128: A plane just crashed. Okay, you said three miles south of Union reserv...
  [129/707] Transcribing C129...
  ✔ C129: Yes, it is a police station. Yes, it is. May I help you? Yes, okay. I ...
  [130/707] Transcribing C130...
  ✔ C130: I know there's an ambulance on the TV for this little boy. Okay. And t...

  ── 130/707 files transcribed ──

  [131/707] Transcribing C131...
  ✔ C131: Hi, we just witnessed the vehicle accident on the Pero tomatoes and pe...
  [132/707] Transcribing C132...
  ✔ C132: There's a horrible accident on 7 mile fare in highway 94....
  [133/707] Transcribing C133...
  ✔ C133: Hi, there was a accident. We just witnessed three cars just been full ...
  [134/707] Transcribing C134...
  ✔ C134: I was told to call my dad to tell whatever I had....
  [135/707] Transcribing C135...
  ✔ C135: He only found his dad's old proofs best, but I don't know....
  [136/707] Transcribing C136...
  ✔ C136: Hello....
  [137/707] Transcribing C137...
  ✔ C137: There has been a murder suicide. There is no survivors. Please send he...
  [138/707] Transcribing C138...
  ✔ C138: यह पलीज वारा हैं वार वार वार वार वार वार वार...
  [139/707] Transcribing C139...
  ✔ C139: Yeah, I'd like to report it to you, please. Okay. Be the thrills....
  [140/707] Transcribing C140...
  ✔ C140: I just shot my wife. Okay, and what's your address?...

  ── 140/707 files transcribed ──

  [141/707] Transcribing C141...
  ✔ C141: Come on, the cow! Please! What's going on? Please, the one who is......
  [142/707] Transcribing C142...
  ✔ C142: A woman came under her house screaming that her son had shot for her h...
  [143/707] Transcribing C143...
  ✔ C143: Hi, I hear a girlfriend just pulled up and there's a guy pull up and t...
  [144/707] Transcribing C144...
  ✔ C144: Hi, Edons, Unshots. We're all on the floor. You're doing what? They th...
  [145/707] Transcribing C145...
  ✔ C145: I'm not talking about this. I'm talking about this. I'm talking about ...
  [146/707] Transcribing C146...
  ✔ C146: Someone with murder, I think. Where are you? No, please, you're gonna ...
  [147/707] Transcribing C147...
  ✔ C147: It was guys just in my mom and my niece and my sister all the while th...
  [148/707] Transcribing C148...
  ✔ C148: I have a gun shop victim here. Okay, I'm going to hurry....
  [149/707] Transcribing C149...
  ✔ C149: I just come in to pick it up my trash and my major is in the house. I'...
  [150/707] Transcribing C150...
  ✔ C150: Тутов dadurch, что в тревоге,...

  ── 150/707 files transcribed ──

  [151/707] Transcribing C151...
  ✔ C151: You need to see this ran over and they said that the boy just shot his...
  [152/707] Transcribing C152...
  ✔ C152: I requested a state police to come out. I would like state police....
  [153/707] Transcribing C153...
  ✔ C153: I had a guy kicking in my door or trying to kick in my front door. I d...
  [154/707] Transcribing C154...
  ✔ C154: in 59 to capture races. There's been a shooting. Somebody came in and ...
  [155/707] Transcribing C155...
  ✔ C155: exit of this game coming from the beach. There's a guy that's complete...
  [156/707] Transcribing C156...
  ✔ C156: There's a naked man or the men's cars way at the end of the car way co...
  [157/707] Transcribing C157...
  ✔ C157: So hi I'm Erie C. I'm Erie C. I'm my great-for-delie....
  [158/707] Transcribing C158...
  ✔ C158: I have a boy that was underwater and he's not breathing. How old is th...
  [159/707] Transcribing C159...
  ✔ C159: Are you inside the house? Yes. Are you alone inside the house? Yes....
  [160/707] Transcribing C160...
  ✔ C160: someone on the back porch of black man. And what is your address? 3613...

  ── 160/707 files transcribed ──

  [161/707] Transcribing C161...
  ✔ C161: I'm gonna take a look at how I put it. How the power of this kit. Well...
  [162/707] Transcribing C162...
  ✔ C162: I'm going to come and stop. Where are you at? I'm at the end....
  [163/707] Transcribing C163...
  ✔ C163: What kind of appearance is that? Your wet? What kind of appearance is ...
  [164/707] Transcribing C164...
  ✔ C164: We had several police tire earlier and did a report....
  [165/707] Transcribing C165...
  ✔ C165: Oh, right, brother. It's having a great time in the hotel. Okay....
  [166/707] Transcribing C166...
  ✔ C166: I just strangled my girlfriend. You just strangled your girlfriend? Ye...
  [167/707] Transcribing C167...
  ✔ C167: Okay, we've had an airboat accident. I'm not sure if they're all injur...
  [168/707] Transcribing C168...
  ✔ C168: Hey, I see a mead down...
  [169/707] Transcribing C169...
  ✔ C169: coral fishermen....
  [170/707] Transcribing C170...
  ✔ C170: I'm going to go now. I'll be right there. Do you have a hand for them?...

  ── 170/707 files transcribed ──

  [171/707] Transcribing C171...
  ✔ C171: HerrÓl, amis. Sie sind komplett die Möglichkeit....
  [172/707] Transcribing C172...
  ✔ C172: I was just going to six temple and there was a I was in the parking lo...
  [173/707] Transcribing C173...
  ✔ C173: Yes, somebody just send my baby please get here. They just did what?...
  [174/707] Transcribing C174...
  ✔ C174: Oh, there's a fucking dead man in the car. Roger for me, young....
  [175/707] Transcribing C175...
  ✔ C175: Can I help you? Somebody who's broken our daughter's trying to break i...
  [176/707] Transcribing C176...
  ✔ C176: Please, before I get through, I have my shirt in here. The shirt is wh...
  [177/707] Transcribing C177...
  ✔ C177: Please fire. 9-1-1. My hands will be having a harder time. Brooke, we'...
  [178/707] Transcribing C178...
  ✔ C178: you. I'll do you off with the shots. With what agency sir?...
  [179/707] Transcribing C179...

### Save Transcription Output

In [15]:
# Save transcripts before doing any NLP — following the tip structure
transcript_df = pd.DataFrame(raw_transcripts)
transcript_df.to_csv("/kaggle/working/transcripts_raw.csv", index=False)

print(f"\n✔ PART 1 COMPLETE")
print(f"  {len(transcript_df)} transcripts saved to transcripts_raw.csv")
print(f"\n  Transcription preview:")
from IPython.display import display
display(transcript_df.head())

# =============================================================================
#  PART 2 — NLP ANALYSIS ON TOP OF TRANSCRIPTIONS
#  Following assignment tip: "Then add keyword extraction and sentiment
#  analysis on top of the transcribed text output"
# =============================================================================

✔ PART 1 COMPLETE
  707 transcripts saved to transcripts_raw.csv

  Transcription preview:

  Call_ID                                          Full_Text
0    C001                                           One just
1    C002  This is the Blocopia Bank in 1302 with the Tra...
2    C003                Yeah? Yeah. Yeah. Yeah. Yeah. Yeah.
3    C004  Yes, we're at the Nelson building and there's ...
4    C005  Listen, we're playing really bad at this. Okay...

### Load NLP Models

In [16]:
print("\n" + "=" * 55)
print("  PART 2 — NLP ON TOP OF TRANSCRIPTIONS")
print("=" * 55)

print("Loading spaCy NER model...")
nlp = spacy.load("en_core_web_sm")

print("Loading HuggingFace sentiment model...")
sentiment_model = pipeline(
    "sentiment-analysis",
    model="distilbert-base-uncased-finetuned-sst-2-english",
    truncation=True,
    max_length=512
)

print("Loading urgency classifier...")
urgency_model = pipeline(
    "zero-shot-classification",
    model="facebook/bart-large-mnli"
)

print("✔ All NLP models loaded\n")

=======================================================
  PART 2 — NLP ON TOP OF TRANSCRIPTIONS
=======================================================
Loading spaCy NER model...

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading HuggingFace sentiment model...

config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

Loading urgency classifier...

config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/1.63G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/515 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

✔ All NLP models loaded

### Keyword Extraction Functions

In [17]:
# Task: Extract keywords — incident type, location mentions, names, urgency phrases

EVENT_MAP = {
    "Building fire / trapped persons": ["fire", "trapped", "flames", "burning", "blaze", "smoke"],
    "Road accident / vehicle crash":   ["accident", "crash", "collision", "hit", "vehicle", "car"],
    "Robbery / theft in progress":     ["robbery", "theft", "stolen", "robber", "burglar", "cash"],
    "Physical assault / fight":        ["fight", "assault", "attack", "stabbing", "shooting", "shot"],
    "Medical emergency":               ["ambulance", "heart attack", "unconscious", "collapsed", "bleeding"],
    "Public disturbance / riot":       ["disturbance", "noise", "crowd", "protest", "riot", "shouting"],
    "Missing person report":           ["missing", "lost", "disappeared", "gone"],
    "Suspicious activity":             ["suspicious", "strange", "following", "lurking"],
}

URGENCY_LABELS = ["very urgent", "moderately urgent", "not urgent"]

def extract_incident_type(text):
    """Extract incident type keyword from transcript."""
    text_lower = text.lower()
    for label, keywords in EVENT_MAP.items():
        if any(kw in text_lower for kw in keywords):
            return label
    return "Unknown incident"

def extract_keywords(text):
    """
    Extract all keywords from transcript:
    - Incident type
    - Location mentions
    - Names (persons)
    - Urgency phrases
    """
    doc = nlp(text)

    # Names from NER
    persons = [e.text for e in doc.ents if e.label_ == "PERSON"]

    # Location mentions from NER
    locations = [e.text for e in doc.ents if e.label_ in ("GPE", "LOC", "FAC")]

    # Urgency phrases — keyword matching
    urgency_words = ["immediately", "urgent", "emergency", "help", "hurry",
                     "now", "trapped", "dying", "bleeding", "unconscious", "danger", "please"]
    urgency_found = [w for w in urgency_words if w in text.lower()]

    # Incident type
    incident = extract_incident_type(text)

    parts = [f"Incident: {incident}"]
    if locations:     parts.append(f"Locations: {', '.join(locations[:3])}")
    if persons:       parts.append(f"Names: {', '.join(persons[:3])}")
    if urgency_found: parts.append(f"Urgency phrases: {', '.join(urgency_found[:4])}")

    return " | ".join(parts)

def extract_location(text):
    """Return first location entity from transcript."""
    doc  = nlp(text)
    locs = [e.text for e in doc.ents if e.label_ in ("GPE", "LOC", "FAC")]
    return locs[0] if locs else "Unknown"

print("✔ Keyword extraction functions defined")

✔ Keyword extraction functions defined

### Sentiment & Urgency Functions

In [18]:
# Task: Perform sentiment/urgency analysis (calm vs distressed)

def get_sentiment(text):
    """
    Sentiment analysis on transcribed text.
    Returns 'Distressed' or 'Calm' — exact assignment format.
    """
    result = sentiment_model(text[:512])[0]
    return "Distressed" if result["label"] == "NEGATIVE" else "Calm"

def get_urgency_score(text):
    """
    Urgency analysis on transcribed text.
    Returns score between 0.0 (not urgent) and 1.0 (very urgent).
    """
    result = urgency_model(text[:512], candidate_labels=URGENCY_LABELS)
    scores = dict(zip(result["labels"], result["scores"]))
    score  = (
        scores.get("very urgent", 0)       * 1.0 +
        scores.get("moderately urgent", 0) * 0.5 +
        scores.get("not urgent", 0)        * 0.1
    )
    return round(score, 2)

print("✔ Sentiment and urgency functions defined")

✔ Sentiment and urgency functions defined

### Run NLP on Top of Transcripts

In [19]:
# Load transcripts saved in Part 1
transcript_df = pd.read_csv("/kaggle/working/transcripts_raw.csv")
print(f"✔ Loaded {len(transcript_df)} transcripts from Part 1")
print(f"\nRunning NLP analysis on all transcripts...\n")

records = []

for i, row in transcript_df.iterrows():
    call_id = row["Call_ID"]
    text    = str(row["Full_Text"]).strip()

    if not text or text == "nan" or text == "":
        continue

    # Transcript excerpt — first 80 chars
    excerpt = (text[:80] + "...") if len(text) > 80 else text

    # Run all NLP tasks on transcribed text
    event         = extract_incident_type(text)   # Incident type
    keywords      = extract_keywords(text)         # All keywords
    location      = extract_location(text)         # Location
    sentiment     = get_sentiment(text)            # Calm vs Distressed
    urgency_score = get_urgency_score(text)        # Urgency score

    records.append({
        "Call_ID":         call_id,
        "Transcript":      excerpt,
        "Extracted_Event": event,
        "Keywords":        keywords,
        "Location":        location,
        "Sentiment":       sentiment,
        "Urgency_Score":   urgency_score,
    })

    if (i + 1) % 20 == 0:
        print(f"  ✔ {i+1} / {len(transcript_df)} processed...")

print(f"\n✔ PART 2 COMPLETE — {len(records)} records processed")

✔ Loaded 707 transcripts from Part 1

Running NLP analysis on all transcripts...

  ✔ 20 / 707 processed...
  ✔ 40 / 707 processed...
  ✔ 60 / 707 processed...
  ✔ 80 / 707 processed...
  ✔ 100 / 707 processed...
  ✔ 120 / 707 processed...
  ✔ 140 / 707 processed...
  ✔ 160 / 707 processed...
  ✔ 180 / 707 processed...
  ✔ 200 / 707 processed...
  ✔ 220 / 707 processed...
  ✔ 240 / 707 processed...
  ✔ 260 / 707 processed...
  ✔ 280 / 707 processed...
  ✔ 300 / 707 processed...
  ✔ 320 / 707 processed...
  ✔ 340 / 707 processed...
  ✔ 360 / 707 processed...
  ✔ 380 / 707 processed...
  ✔ 400 / 707 processed...
  ✔ 420 / 707 processed...
  ✔ 440 / 707 processed...
  ✔ 460 / 707 processed...
  ✔ 480 / 707 processed...
  ✔ 500 / 707 processed...
  ✔ 520 / 707 processed...
  ✔ 540 / 707 processed...
  ✔ 560 / 707 processed...
  ✔ 580 / 707 processed...
  ✔ 600 / 707 processed...
  ✔ 620 / 707 processed...
  ✔ 640 / 707 processed...
  ✔ 660 / 707 processed...
  ✔ 680 / 707 processed...
  ✔ 700 / 707 processed...

✔ PART 2 COMPLETE — 704 records processed

In [20]:
# Fix Event Extraction — broader keyword matching for short transcripts
EXTENDED_EVENT_MAP = {
    "Building fire / trapped persons": ["fire", "trapped", "flame", "burn", "smoke", "blaze", "911 fire"],
    "Road accident / vehicle crash":   ["accident", "crash", "collision", "hit", "car", "vehicle", "truck", "road"],
    "Robbery / theft in progress":     ["robbery", "rob", "theft", "steal", "stolen", "burglar", "break", "bank", "cash"],
    "Physical assault / fight":        ["fight", "assault", "attack", "stab", "shoot", "gun", "hit", "hurt", "beat"],
    "Medical emergency":               ["ambulance", "heart", "unconscious", "collapse", "bleed", "hurt", "pain", "sick", "dying", "fell"],
    "Public disturbance / riot":       ["disturbance", "noise", "crowd", "protest", "riot", "shout", "yell", "loud"],
    "Missing person report":           ["missing", "lost", "disappear", "gone", "find", "child", "kid"],
    "Suspicious activity":             ["suspicious", "strange", "follow", "lurk", "watching", "weird"],
}

def extract_event_improved(text):
    text_lower = text.lower()
    for label, keywords in EXTENDED_EVENT_MAP.items():
        if any(kw in text_lower for kw in keywords):
            return label
    return "Unknown incident"

def extract_location_improved(text):
    # Try spaCy NER first
    doc  = nlp(text)
    locs = [e.text for e in doc.ents if e.label_ in ("GPE", "LOC", "FAC")]
    if locs:
        return locs[0]
    # Fallback — look for common location words
    location_hints = ["street", "avenue", "road", "building", "park",
                      "downtown", "highway", "house", "store", "bank", "hospital"]
    words = text.lower().split()
    for i, word in enumerate(words):
        if word in location_hints and i > 0:
            return words[i-1].title() + " " + word.title()
    return "Unknown"

# Re-process all records with improved functions
for record in records:
    # Find original full text
    match = transcript_df[transcript_df["Call_ID"] == record["Call_ID"]]
    if not match.empty:
        full_text = str(match.iloc[0]["Full_Text"])
        record["Extracted_Event"] = extract_event_improved(full_text)
        record["Location"]        = extract_location_improved(full_text)

# Rebuild output
output_df     = pd.DataFrame(records)
assignment_df = output_df[["Call_ID", "Transcript", "Extracted_Event",
                            "Location", "Sentiment", "Urgency_Score"]].copy()

# Save updated CSV
assignment_df.to_csv("/kaggle/working/audio_output.csv", index=False)

from IPython.display import display
print("✔ Updated output with improved extraction:")
display(assignment_df.head(10))

✔ Updated output with improved extraction:

,Call_ID,Transcript,Extracted_Event,Location,Sentiment,Urgency_Score
0,C001,One just,Unknown incident,Unknown,Calm,0.31
1,C002,This is the Blocopia Bank in 1302 with the Tra...,Robbery / theft in progress,Blocopia Bank,Distressed,0.51
2,C003,Yeah? Yeah. Yeah. Yeah. Yeah. Yeah.,Unknown incident,Unknown,Calm,0.51
3,C004,"Yes, we're at the Nelson building and there's ...",Unknown incident,Nelson Building,Calm,0.59
4,C005,"Listen, we're playing really bad at this. Okay...",Unknown incident,Unknown,Distressed,0.67
5,C006,我是 我是 我是 我是 Dr. Dr. Dr. Your Dr. Dr. Dr. Dr. D...,Unknown incident,Unknown,Distressed,0.54
6,C007,I'm locking in the field and I'm looking for a...,Missing person report,Unknown,Distressed,0.58
7,C008,On vient se faire voir verser à mes magies. drink,Unknown incident,Unknown,Distressed,0.47
8,C009,"Emersing you've got it, I would always be shut...",Unknown incident,Unknown,Distressed,0.59
9,C010,"Okay, it's out of the bizzani, we'll grab any ...",Unknown incident,Unknown,Distressed,0.58

### Save Final Output CSV

In [21]:
output_df = pd.DataFrame(records)

# Save full output (with keywords)
output_df.to_csv("/kaggle/working/audio_full_output.csv", index=False)

# Save assignment output — exact columns from assignment
assignment_df = output_df[["Call_ID", "Transcript", "Extracted_Event",
                             "Location", "Sentiment", "Urgency_Score"]].copy()
assignment_df.to_csv("/kaggle/working/audio_output.csv", index=False)

print(f"\n✔ audio_output.csv        — {len(assignment_df)} records (submit this)")
print(f"✔ audio_full_output.csv   — includes extracted keywords")
print(f"✔ transcripts_raw.csv     — raw Whisper transcriptions")

print(f"\n{'='*55}")
print("  STRUCTURED OUTPUT TABLE (first 10 rows)")
print(f"{'='*55}")
from IPython.display import display
display(assignment_df.head(10))

✔ audio_output.csv        — 704 records (submit this)
✔ audio_full_output.csv   — includes extracted keywords
✔ transcripts_raw.csv     — raw Whisper transcriptions

=======================================================
  STRUCTURED OUTPUT TABLE (first 10 rows)
=======================================================

,Call_ID,Transcript,Extracted_Event,Location,Sentiment,Urgency_Score
0,C001,One just,Unknown incident,Unknown,Calm,0.31
1,C002,This is the Blocopia Bank in 1302 with the Tra...,Robbery / theft in progress,Blocopia Bank,Distressed,0.51
2,C003,Yeah? Yeah. Yeah. Yeah. Yeah. Yeah.,Unknown incident,Unknown,Calm,0.51
3,C004,"Yes, we're at the Nelson building and there's ...",Unknown incident,Nelson Building,Calm,0.59
4,C005,"Listen, we're playing really bad at this. Okay...",Unknown incident,Unknown,Distressed,0.67
5,C006,我是 我是 我是 我是 Dr. Dr. Dr. Your Dr. Dr. Dr. Dr. D...,Unknown incident,Unknown,Distressed,0.54
6,C007,I'm locking in the field and I'm looking for a...,Missing person report,Unknown,Distressed,0.58
7,C008,On vient se faire voir verser à mes magies. drink,Unknown incident,Unknown,Distressed,0.47
8,C009,"Emersing you've got it, I would always be shut...",Unknown incident,Unknown,Distressed,0.59
9,C010,"Okay, it's out of the bizzani, we'll grab any ...",Unknown incident,Unknown,Distressed,0.58

### Verify Output Columns

In [22]:
print(f"\n{'='*55}")
print("  OUTPUT COLUMNS CHECK")
print(f"{'='*55}")
expected = ["Call_ID", "Transcript", "Extracted_Event",
            "Location", "Sentiment", "Urgency_Score"]
for col in expected:
    status = "✔" if col in assignment_df.columns else "❌"
    print(f"  {status} {col}")

print(f"\n{'='*55}")
print("  SENTIMENT DISTRIBUTION")
print(f"{'='*55}")
display(assignment_df["Sentiment"].value_counts().reset_index())

print(f"\n✔ Download audio_output.csv from Output panel on the right")
print(f"  Share with your team for the integration step.")

=======================================================
  OUTPUT COLUMNS CHECK
=======================================================
  ✔ Call_ID
  ✔ Transcript
  ✔ Extracted_Event
  ✔ Location
  ✔ Sentiment
  ✔ Urgency_Score

=======================================================
  SENTIMENT DISTRIBUTION
=======================================================

    Sentiment  count
0  Distressed    539
1        Calm    165

✔ Download audio_output.csv from Output panel on the right
  Share with your team for the integration step.

In [23]:

# ── FIX: Re-apply improved event extraction to all records ───────────────────
import pandas as pd
from IPython.display import display

audio_df = pd.read_csv("/kaggle/working/audio_output.csv")
print(f"Loaded {len(audio_df)} audio records")

EXTENDED_EVENT_MAP = {
    "Building fire / trapped persons": ["fire", "trapped", "flame", "burn", "smoke", "blaze"],
    "Road accident / vehicle crash":   ["accident", "crash", "collision", "hit", "car", "vehicle", "truck", "road"],
    "Robbery / theft in progress":     ["robbery", "rob", "theft", "steal", "stolen", "burglar", "break", "bank", "cash"],
    "Physical assault / fight":        ["fight", "assault", "attack", "stab", "shoot", "gun", "hit", "hurt", "beat"],
    "Medical emergency":               ["ambulance", "heart", "unconscious", "collapse", "bleed", "hurt", "pain", "sick", "dying", "fell"],
    "Public disturbance / riot":       ["disturbance", "noise", "crowd", "protest", "riot", "shout", "yell", "loud"],
    "Missing person report":           ["missing", "lost", "disappear", "gone", "find", "child", "kid"],
    "Suspicious activity":             ["suspicious", "strange", "follow", "lurk", "watching", "weird"],
}

def fix_event(text):
    """Apply improved event extraction — replaces Unknown incident."""
    text_lower = str(text).lower()
    for label, keywords in EXTENDED_EVENT_MAP.items():
        if any(kw in text_lower for kw in keywords):
            return label
    return "General Emergency"  # Better than Unknown incident

# Apply improved extraction to Transcript column
audio_df["Extracted_Event"] = audio_df["Transcript"].apply(fix_event)

# Save fixed output
audio_df.to_csv("/kaggle/working/audio_output.csv", index=False)

print("\n✔ Event extraction fixed!")
print("\n  Event Distribution:")
display(audio_df["Extracted_Event"].value_counts().reset_index().rename(
    columns={"index": "Event", "Extracted_Event": "Count"}
))
print("\n  Output Table (first 10 rows):")
display(audio_df[["Call_ID", "Transcript", "Extracted_Event",
                   "Location", "Sentiment", "Urgency_Score"]].head(10))

Loaded 704 audio records

✔ Event extraction fixed!

  Event Distribution:

                             Count  count
0                General Emergency    465
1    Road accident / vehicle crash     65
2         Physical assault / fight     53
3  Building fire / trapped persons     35
4      Robbery / theft in progress     28
5                Medical emergency     25
6            Missing person report     22
7              Suspicious activity      6
8        Public disturbance / riot      5

  Output Table (first 10 rows):

,Call_ID,Transcript,Extracted_Event,Location,Sentiment,Urgency_Score
0,C001,One just,General Emergency,Unknown,Calm,0.31
1,C002,This is the Blocopia Bank in 1302 with the Tra...,Robbery / theft in progress,Blocopia Bank,Distressed,0.51
2,C003,Yeah? Yeah. Yeah. Yeah. Yeah. Yeah.,General Emergency,Unknown,Calm,0.51
3,C004,"Yes, we're at the Nelson building and there's ...",General Emergency,Nelson Building,Calm,0.59
4,C005,"Listen, we're playing really bad at this. Okay...",General Emergency,Unknown,Distressed,0.67
5,C006,我是 我是 我是 我是 Dr. Dr. Dr. Your Dr. Dr. Dr. Dr. D...,General Emergency,Unknown,Distressed,0.54
6,C007,I'm locking in the field and I'm looking for a...,General Emergency,Unknown,Distressed,0.58
7,C008,On vient se faire voir verser à mes magies. drink,General Emergency,Unknown,Distressed,0.47
8,C009,"Emersing you've got it, I would always be shut...",General Emergency,Unknown,Distressed,0.59
9,C010,"Okay, it's out of the bizzani, we'll grab any ...",General Emergency,Unknown,Distressed,0.58